== Subject

The OGC Interoperable Simulation and Gaming Sprint advanced the use of relevant OGC and Khronos standards in the modeling and simulation community through practical exercise and testing of the OGC API - GeoVolumes draft specification produced by the https://docs.ogc.org/per/20-031.html[3D Data Container and Tiles API Pilot]. Of particular interest was the handling and integration of glTF models coming from multiple sources, but the sprint also examined the specification’s implementability, consistency, completeness, and maturity.

== Executive Summary

(( The following is, as all texts in double square brackets, a helper text. Please remove this and all other helper texts once done. ))

(( **This can only be written after the Findings and Future Recommendations.** ))

(( The Executive Summary clause shall contain the key findings and results in a concise form. A more detailed description of the findings should be in the body of the report. ))

(( The Executive Summary shall contain a business value statement that should describe the value of this Engineering Report to improve interoperability, advance location-based technologies or realize innovations. ))

(( This section shall include precise descriptions of the requirements that have been addressed by the work documented in this Engineering Report; together with the research motivation that answers the fundamental question: What motivated us to address this topic in this report? ))

(( This section provides an overview of recommendations on how to further proceed with the achievements documented in this ER. ))

(( This section shall be between 1-3 pages.))

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
| Name | Organization | Role
| Leonard Daly | Daly Realism representing Khronos Group  | Contributor & Editor
| Holly Black | CAE | Contributor
| Sean Lilley | Cesium | Contributor
| Michala Hill | Cognitics | Contributor
| Jerome St-Louis | Ecere | Contributor
| Anneley Hadland | Helyx | Contributor
| Emeric Beaufays | Hexagon | Contributor
| Joshua Rentrope | InfoDao | Contributor
| Jordan Dauble   | SimBlocks.io | Contributor
| Patrick Caughey | SimBlocks.io | Contributor
| Barbara Cotter  | SimBlocks.io | Contributor
| Glenn Johnson   | SimBlocks.io | Contributor
| Joseph Kaile    | SimBlocks.io | Contributor
| Volker Coors                    | Steinbeis, HFT Stuttgart | Contributor
| Thunyathep Santhanavanich (Joe) | Steinbeis, HFT Stuttgart | Contributor
| Harpreet Singh                  | Steinbeis, HFT Stuttgart | Contributor
| Patrick Würstle                 | Steinbeis, HFT Stuttgart | Contributor
| Scott Serich | Open Geospatial Consortium | Contributor & Editor
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
