== Terms and definitions

For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

&#9679; OGC Pilot ::

 OGC Pilots apply and test OGC standards in real world environments. Pilot projects are an opportunity for users to understand how to best address their requirements using standards-based architectures. A Pilot evaluates the feasibility of implementing a standards-based architecture and provides valuable requirements for defining and developing solicitations or tenders for implementation of an operational system. Pilots usually work with prototypes or pre-production products that are explored in realistic scenarios.

 &#9679; OGC Sprint ::

  OGC Sprints experiment with emerging ideas in the context of geospatial standards, help improve interoperability of existing standards by experimenting with new extensions or profiles, are used as proof of concept for other OGC Innovation Program initiatives, or support OGC Standards Program activities. OGC Sprints are very short and focused initiatives that are often executed within few days to weeks. Sprints put most of their emphasis on the agile development phase that is usually executed during a physical meeting.

&#9679; 3D Tiles ::

&#9679; b3dm ::
Batched 3D Models

&#9679; CDB ::
A dataset standard for ...

&#9679; Full Motion Video (FMV) ::

&#9679; GeoVolume ::

&#9679; IANA ::
Internet Assigned Numbers Authority is the organization responsible for oversight of the architecture of the Internet. They are ultimately responsible for assignment of IP addresses and management of Media Types

&#9679; jp2 | JPEG2000 ::
It is an advanced lossy compression algorithm for representing 2D data. It is currently not widely supported in browsers, requiring a (CPU-intensive) conversion to JPEG or PNG/GIF.

&#9679; OpenFlight ::

&#9679; URL/URI ::
At one time Uniform Resource Location (URL) was a subset of Uniform Resource Identifier (URI). Now both are considered the same cite:[URIURL].

&#9679; W3C ::
World Wide Web Consortium is responsbile for all standards that make the Web operate, including URIs, HTTP, etc.
