== Terms and definitions



For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

.NOTE: Delete the first three terms because they are examples.

&#9679; OGC Pilot ::

 OGC Pilots apply and test OGC standards in real world environments. Pilot projects are an opportunity for users to understand how to best address their requirements using standards-based architectures. A Pilot evaluates the feasibility of implementing a standards-based architecture and provides valuable requirements for defining and developing solicitations or tenders for implementation of an operational system. Pilots usually work with prototypes or pre-production products that are explored in realistic scenarios.

 &#9679; OGC Sprint ::

  OGC Sprints experiment with emerging ideas in the context of geospatial standards, help improve interoperability of existing standards by experimenting with new extensions or profiles, are used as proof of concept for other OGC Innovation Program initiatives, or support OGC Standards Program activities. OGC Sprints are very short and focused initiatives that are often executed within few days to weeks. Sprints put most of their emphasis on the agile development phase that is usually executed during a physical meeting.

&#9679; term name ::

 text of the definition

&#9679; term name|synonym  ::

 text of the definition


===	Abbreviated terms

.NOTE: The abbreviated terms clause gives a list of the abbreviated terms and the symbols necessary for understanding this document. All symbols should be listed in alphabetical order. Some more frequently used abbreviated terms are provided below as examples.

* COM	Component Object Model
* CORBA	Common Object Request Broker Architecture
* COTS	Commercial Off The Shelf
* DCE	Distributed Computing Environment
* DCOM	Distributed Component Object Model
* IDL	Interface Definition Language
