[[Findings]]
== Findings

=== Introduction

This section describes findings of the Sprint participants. All findings presented here are significant in that there were reported by at least two participants or serious issues reported by a single participant. 

Due to the nature of the Sprint, not all participants investigated the same aspects of the draft Specification. This is considered a positive aspect of the Sprint in that with limited resources a fairly expansive coverage of the draft Specification was performed.

=== Aspects of Investigation

Each participant was free to choose which one (or more) scenarios to pursue. <<discussion-of-scenarios,Three scenarios>> were discussed in the CfP. Participants could also create their own. OGC reviewed each participants proposal and suggested revisions to better align with the goals of the Sprint, interest of the Sponsor, and coverage by the other participants. <<table-particiapnt-scenarios>> shows the coverage of scenarios by the participants.

[#table-scenario-summary,reftext='{table-caption} {counter:table-num}']
.A summary of the scenarios used during the Sprint. Scenarios 1-3 were in the Call for Proposals. Other-1 and Other-2 were proposed by Cognitics and SimBlocks, respectively.
[cols="^1,<6",options="header",align="center"]
|===
|Scenario ^|Summary Desription
|1 | Investigate model and terrain updates
|2 | Investigate alternate and multiple distributions 
|3 | Investigate organization of underlying 3D data
|Other-1 | Investigate integration with Rapid3D (Full Motion Video)
|Other-2 | Investigate the integration of GeoVolumes API with Unity game engine
|===

[#table-particiapnt-scenarios,reftext='{table-caption} {counter:table-num}']
.The pre-declared the scenarios for each particiapnt. These are the primary areas of work, though their work may have touched on other scenarios. Cognitics worked with creating models from full-motion video (Other-1), and SimBlocks worked with their Unity integration (Other-2). The participant name links to their report section.
[cols="2,^1,^1,^1,^1",options="header",align="center"]
|===
|*Participant* |*Scenario 1*  |*Scenario 2*  |*Scenario 3*  |*Other*
|<<cae,*CAE*>>                             |*&check;* | | |
|<<cesium,*Cesium*>>                       |*&check;* | | |
|<<cognitics-sprint-report,*Cognitics*>>   | | |*&check;* |*1*
|<<ecere,*Ecere*>>                         |*&check;* | | |
|<<helyx-sprint-report,*Helyx*>>           | |*&check;* | |
|<<hexagon-gsp,*Hexagon*>>                 |*&check;* | | |
|<<infodao-sprint-report,*InfoDao*>>       | |*&check;* |*&check;* |
|<<simblocksio-sprint-report,*SimBlocks*>> | | | |*2*
|<<steinbeis-sprint-report,*Steinbeis*>>   |*&check;* | |*&check;* |
|===

=== Cooperative Efforts

All participants cooperated with each other in various aspects of the Sprint. This included a team entry, providing data services for the Sprint, and use and testing of other OGC API services.

Two teams were formed. Three particpants teamed together for the Sprint to produce a combined result. These were CAE, Cesium, and Cognitics. This was done with the knowledge and approval of the sponsor. A two participant team (Ecere and Steinbeis) was formed to test the insertion, modification, and deletion of 3D objects and terrain into the base scene.

All participants cooperated and included the test and use of other particiapnts services during the Sprint. Use and testing was performed by all members agains OGC GeoVolumes API services offered by others. <<table-tie-summary>> shows the interoperation between offered services (servers) and use (clients).

[#table-tie-summary,reftext='{table-caption} {counter:table-num}']
.The inter-participant testing is shown here. The Client is show across the table with the Service provider going down. *&check;* means that the server was able to successfully deliver and the client was to successfully receive the data when using the GeoVolume API. The text in brackets indicate the data that was transferred. [pilot] means the data used during the Pilot project (primary New York City). This table summarizes the information presented in <<annex-a,Annex A: TIE Results>>.
[cols="1,2,2,2,2",options="header",align="center"]
|===
>| *Client ->* .2+^| *Hexagon* .2+^| *InfoDao* .2+^| *SimBlocks* .2+^| *Steinbeis*
<| *Service*

| *Cesium*
  | *&check;* (+ fdbk)
  | *&check;* [pilot]
  | *&check;* [pilot]
  | *&check;* [pilot]

| *Cognitics*
  | *&check;* [pilot]
  | NA
  | *&check;* [pilot]
  | *&check;* [pilot]

| *Ecere*
  | *&check;* [San Diego]
  | *&check;* [San Diego]
  | *&check;* [San Diego]
  | *&check;* [San Diego]

|  _(Pilot functions)_ *Ecere*
  | *&check;* [pilot]
  | *&check;* [pilot]
  | *&check;* [pilot]
  | *&check;* [pilot]

| *PyGeoAPI-InfoDao*
  | *&check;*
  | using CDB server
  | NA
  | not pass

| *Helyx*
  | *&check;* [pilot, San Diego]
  | *&check;* [pilot, San Diego]
  | *&check;* [pilot, San Diego]
  | *&check;* [pilot, San Diego]

| *Steinbeis New*

  | *&check;*(+ fdbk)
  | *&check;* [San Diego]
  | *&check;* [San Diego]
  | *&check;* [San Diego]

| _(Pilot functions)_ *Steinbeis Existing*
  | *&check;* [pilot]
  | *&check;* [pilot]
  | *&check;* [pilot]
  | *&check;* [pilot]

|===

=== General Results

The work done for the Sprint was closely tied to the work done for the Pilot, even though some of the participants were different between the two projects. The mix of participants allowed some with extensive experience in GeoVolumes to dig deeper into areas that were not fully explored during the Pilot. The participants without the Pilot brought a fresh read to the document and potential solutions.

No defects in the draft specification were discovered, though several items need further investigation. These are discussed in the <<Discovered Inconsistencies>> section. Several participants discussed the importance of GeoVolumes following the OGC API Core, Volume 2: 3D Data specification to ensure compatibility throughout the suite of OGC APIs.

In addition to the results shown in <<table-tie-summary>> the participants were able to use their existing GeoVolume client sofware to access data-stores that had not been previously used by OGC and OGC projects. These data-stores included data in CDB and other formats that either were served directly (as 3D Tiles static files) or generated on-the-fly from CDB and other sources.

It is worth mentioning that two participants (CAE & Cognitics) have hosted their services on Amazon Web Services (AWS) to improve through-put and allow for easy load expansion when needed. The use of cloud services was smooth and without issues. These were not tested for heavy loads or load balancing capabilities or performance.

=== Dynamic Dataset Updates

Several of the participants developed the capability to update part of the dataset during operation. These updates do not require regeneration of the entire dataset from the data-store. There are mechanisms to ensure that any generated and cached files are appropriately rebuilt on the next request. 

Ecere, Steinbeis, and Hexagon addressed the insert/update/removal  models using the _OGC API - Features_. The specified API proved sufficient (but not necessarily iedal) to perform these functions within the context of GeoVolume API and the Sprint. Ecere proposed an extension that provided a better interface to refer to models. All of these participants did not that getting the models to allign with the local terrain was not a simple matter and required different solutions depending on how the client was designed and configured.

=== Performance Issues

Nearly all of the participants noted that conversion of CDB to 3D Tiles was an expensive operation and needed to be avoided especially for on-the-fly requests. Cesium noted that in addition to the performance issues associated with conversion, the high-detailed building files are (generally) very large (50-100MB), and improving the tiling scheme is needed to maintain performance of the server and client.

=== Discovered Inconsistencies

Several of the participants discovered various issues related to HTTP transactions. These include issues in the URL, request method, content-type, and, request attributes. The issues and possible solutions are inter-related. Each issue is linked to the section of the participants report where it is discussed in detail.

==== URLs

Issues with the URL were noted by several participants. These include 

* _SimBlocks -- server inconsitencies_
* _Ecere - need better way for merging?_
* _InfoDao_
* Clarity of requirements for endpoints. Helyx observed (<<representing-alternate-distributions-at-the-collections-level,Representing Alternate Distributions at the Collection(s) Level>>) that there is a lack of clarity in how to specify the alternet distributions. It may be specified as the final element in a path (endpoint), via search parameters, or through content-type negotiation.
* Conflicts between OGC specifications and operating system requirements for use of the characters `/` (slash) and `:` (colon).  [Helyx: <<A note on Path Format>>].

NOTE: "Uniform Resource Identifier (URI): Generic Syntax" site:[RFC3986] specifies that the colon (":") is a reserved character and needs to be URL-encoded. This requirement may be sufficient for URI access, but if the system needs to support static file-mode access; there may be issues with Windows-based servers.

==== Request Methods

Use of request methods may not agree with W3C definitions

* _Ecere - model state change_


==== Media Type

The HTTP specification allows the client to specify the allowed media types that the server is allowed to return. The server may return a "Not Found" or other responses if the requested media type for that content is not available. If the various 3D data types have unique media types, the client may request a specific one through this mechanism. Helyx discussed some of these options in <<Representing Alternate Distributions as Media Types>>.

NOTE: Content types do not have to be IANA approved. There are provision for experimental and vendor-specific content types. It is generally easier to get IANA approval after a specification is approved by standards organization.

==== Request attributes

HTTP allows for an alternate or roll-over reference. This allows for the client code to indicate alternate distributions of the content-equivalent data. For example the primary reference may be 3D Tiles with a roll-over of i3s and CDB. Helyx discussed some of the issues and options in <<Representing Alternate Distributions within one API - Link Relations>>.

=== Game Engine Interface

SimBlocks.io work on integrating their solution into the Unity game engine. There was quite a bit of work to do bringing in the 3D data as glTF or 3D Tiles into Unity. The solution they developed during the Sprint is sub-optimal, but it did work. They reported that they felt the solution for the Unreal engine would be a similar amount of work.


=== Editor's Observations (Conclusions?)

The basics of the GeoVolume draft specification are complete and well-specificed (consistent and complete). There may still be some edge cases that are poorly defined there were not investigated in the Sprint. A number of the participants indicated the importance of GeoVolumes and other OGC APIs to retain full consistency and compatibility with OGC Common API, especially Part 2 - 3D Data.

Several participants noted issues with URLs and other HTTP issues. In a review of the statements by the participants and OGC API documents, it appears that various HTTP capabilities are not fully, correctly, or completely specified. This is highlighted in the <<Discovered Inconsistencies>> section. HTTP provides definitions for URLs, request methods, content types, and request attributes. Their use does not appear to be fully defined in the various OGC APIs. 

Perhaps a more serious problem is with the location and data content naming convention. There appears to be substantial flexibility in the naming of locations and data that two different servers could have significantlly different naming for the same data at the same location. If there is an intent to form a large federation of servers from different organization, that naming convention needs further definition.

OGC needs to be aware of Best Current Practice "URI Design and Ownership" cite:[RFC8820] that state the the best practice is to not specify the path of an application as that is the responsibility of the URI owner (generally the owner of the [sub-]domain).

Finally it was shown that GeoVolumes could be integrated with a game engine (Unity). This would allow other clients to easily access the API with the need for extensive graphics development. It was hypothesized that the effort to integrate with Unreal would be similar. 


== *_Check to see if there are any other topics_*