[[Findings]]
== Findings

=== Introduction

This section describes findings of the Sprint participants. Each finding presented here is significant in that is was reported by at least two participants or it was a serious issue reported by a single participant.

Not all participants investigated the same aspects of the draft Specification. This approach enabled fairly expansive testing of the draft Specification and related areas.

=== Aspects of Investigation

Each participant was free to choose which one (or more) scenarios to pursue. https://portal.ogc.org/files/?artifact_id=94059#SprintScenario[Three scenarios] were discussed in the CfP cite:[SprintCfP]. Participants could also create their own scenario. OGC reviewed each participant's proposal and suggested revisions to better align with the goals of the Sprint, the interest of the Sponsor, and the coverage by the other participants. <<table-scenario-summary>> provides a summary description of the selected scenarios. <<table-participant-scenarios>> shows the coverage of scenarios by the participants.

[#table-scenario-summary,reftext='{table-caption} {counter:table-num}']
.A summary of the scenarios used during the Sprint. Scenarios 1-3 were in the Call for Participation. Other-1 and Other-2 were proposed by Cognitics and SimBlocks, respectively.
[cols="^1,<6",options="header",align="center"]
|===
|Scenario ^|Summary Desription
|1 | Investigate model and terrain updates
|2 | Investigate alternate and multiple distributions
|3 | Investigate organization of underlying 3D data
|Other-1 | Investigate integration with Rapid3D (Full Motion Video)
|Other-2 | Investigate the integration of GeoVolumes API with Unity game engine
|===

[#table-participant-scenarios,reftext='{table-caption} {counter:table-num}']
.The pre-declared the scenarios for each participant. These are the primary areas of work, though their work may have touched on other scenarios. Cognitics worked with creating models from full-motion video (Other-1), and SimBlocks worked with their Unity integration (Other-2). The participant name links to their report section.
[cols="2,^1,^1,^1,^1",options="header",align="center"]
|===
|*Participant* |*Scenario 1*  |*Scenario 2*  |*Scenario 3*  |*Other*
|<<CAE,CAE>> ^|*&#10003;* | | |
|<<Cesium,Cesium>> ^|*&#10003;* | | |
|<<Cognitics,Cognitics>> ^| | ^|*&#10003;* ^|*1*
|<<Ecere,Ecere>> ^|*&#10003;* | | |
|<<Helyx,Helyx>> ^| ^|*&#10003;* | |
|<<Hexagon,Hexagon>> ^|*&#10003;* | | |
|<<InfoDao,InfoDao>> ^| ^|*&#10003;* ^|*&#10003;* |
|<<SimBlocks,SimBlocks>> ^| | | ^|*2*
|<<Steinbeis,Steinbeis>> ^|*&#10003;* | ^|*&#10003;* |
|===

=== Cooperative Efforts

All participants cooperated with each other in various aspects of the Sprint. This included a team entry, providing data services for the Sprint, and use and testing of other OGC API services.

Two teams were formed. Three participants,  CAE, Cesium, and Cognitics, teamed together to produce a combined result. This was done with the knowledge and approval of the sponsor. A two participant team (Ecere and Steinbeis) was formed to test the insertion, modification, and deletion of 3D objects and terrain into the base scene.

All participants cooperated and included the test and use of other participant services during the Sprint. Use and testing was performed by all members agains OGC GeoVolumes API services offered by others. <<table-tie-summary>> shows the interoperation between offered services (servers) and uses (clients).

[#table-tie-summary,reftext='{table-caption} {counter:table-num}']
.The inter-participant testing is shown here. The Client is show across the table with the Service provider going down. *&#10003;* means that the server was able to successfully deliver and the client was to successfully receive the data when using the GeoVolume API. The text in brackets indicate the data that was transferred. [pilot] means the data used during the Pilot project (primarily New York City). This table summarizes the information presented in the <<TechnologyIntegrationExperimentsTable,Technology Integration Experiment (TIE) Table>>.
[cols="2,3,3,3,3",options="header",align="center"]
|===
>| *Client ->* .2+^| *Hexagon* .2+^| *InfoDao* .2+^| *SimBlocks* .2+^| *Steinbeis*
<| *Service*

| *Cesium*
  | *&#10003;* (+ fdbk)
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]

| *Cognitics*
  | *&#10003;* [pilot]
  | NA
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]

| *Ecere*
  | *&#10003;* [San Diego]
  | *&#10003;* [San Diego]
  | *&#10003;* [San Diego]
  | *&#10003;* [San Diego]

|  _(Pilot functions)_ *Ecere*
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]

| *PyGeoAPI-InfoDao*
  | *&#10003;*
  | using CDB server
  | NA
  | not pass

| *Helyx*
  | *&#10003;* [pilot, San Diego]
  | *&#10003;* [pilot, San Diego]
  | *&#10003;* [pilot, San Diego]
  | *&#10003;* [pilot, San Diego]

| *Steinbeis New*

  | *&#10003;*(+ fdbk)
  | *&#10003;* [San Diego]
  | *&#10003;* [San Diego]
  | *&#10003;* [San Diego]

| _(Pilot functions)_ *Steinbeis Existing*
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]
  | *&#10003;* [pilot]

|===

=== General Results

The work done for the Sprint was closely tied to the work done for the Pilot, even though some of the participants were different between the two initiatives. The mix of participants allowed some with extensive experience in GeoVolumes to dig deeper into areas that were not fully explored during the Pilot. Participants who were not part of the Pilot brought a fresh read to the document along with potential solutions.

No defects in the draft specification were discovered, though several items need further investigation. These are discussed in the <<Discovered Inconsistencies>> section. Several participants discussed the importance of GeoVolumes following the OGC API Core, Volume 2: 3D Data specification to ensure compatibility throughout the suite of OGC APIs.

In addition to the results shown in <<table-tie-summary>> the participants were able to use their existing GeoVolume client software to access data-stores that had not been previously used by OGC and OGC projects. These data-stores included data in CDB and other formats that either were served directly (as 3D Tiles static files) or generated on-the-fly from CDB and other sources.

Steinbeis extended one of the scenarios to include the integration of https://www.ogc.org/standards/sensorthings[SensorThings API] cite:[SensorThings] to illustrate how these two APIs could work together (<<SensorThings API Server for Urban Mobility>>). There were no inconsistencies or other issues found.

It is worth mentioning that two participants (CAE & Cognitics) have hosted their services on Amazon Web Services (AWS) to improve throughput and allow for easy load expansion when needed. The use of cloud services was smooth and without issues. These were not tested for heavy loads, load balancing capabilities, or performance.

=== Dynamic Dataset Updates

Several of the participants developed the capability to update part of the dataset during operation. These updates do not require regeneration of the entire dataset from the data-store. There are mechanisms to ensure that any generated and cached files are appropriately rebuilt on the next request.

Ecere, Steinbeis, and Hexagon addressed the insert/update/removal models using the https://www.ogc.org/standards/ogcapi-features[OGC API - Features] standard. The specified API proved sufficient (but not necessarily ideal) to perform these functions within the context of GeoVolume API and the Sprint. Ecere proposed an extension that provided a better interface to refer to models. All of these participants did note that getting the models to align with the local terrain was not a simple matter and required different solutions depending on how the client was designed and configured.

=== Performance Comments

Nearly all of the participants noted that conversion of CDB to 3D Tiles was an expensive operation and needed to be avoided especially for on-the-fly requests. Cesium noted that in addition to the performance issues associated with conversion, the high-detailed building files are (generally) very large (50-100MB), and improving the tiling scheme is needed to maintain performance of the server and client.

Another issue noted by Ecere and Cesium (among others) was handling the creation of glTF files. In particular the manipulation of meshes. Some of the supporting libraries may require a particular condition (e.g., each mesh only uses a single material) while the output may require a single mesh with multiple materials.

=== Discovered Inconsistencies

Several of the participants discovered various issues related to HTTP transactions. These include issues in the URL, request method, content-type, and, request attributes. The issues and possible solutions are interrelated. Each issue is linked to the section of the participants report where it is discussed in detail.

==== URLs

Issues with the URL were noted by several participants. These include

* Different servers using GeoVolumes API use different relative URLs for models. In some cases it is a full path, other cases it is relative to the current document. It is consistent within a sever. SimBlocks discusses this in <<Server Testing>>.
* The end-point requirements for are not always sufficiently clear. Helyx observed (<<RepresentingAlternateDistributionsAtCollectionsLevel,Representing Alternate Distributions at the Collection(s) Level>>) that there is a lack of clarity in how to specify the alternate distributions. It may be specified as the final element in a path (endpoint), via search parameters, or through content-type negotiation.
* Conflicts between OGC specifications and operating system requirements for use of the characters `/` (slash) and `:` (colon). See the Helyx <<NoteOnPathFormat,A note on Path Format>>.

NOTE: "Uniform Resource Identifier (URI): Generic Syntax" cite:[RFC3986] specifies that the colon (":") is a reserved character and needs to be URL-encoded. This requirement may be sufficient for URI access, but if the system needs to support static file-mode access; there may be issues with Windows-based servers.

==== Request Methods

Ecere, Steinbeis, and Hexagon investigated providing model and terrain change services. These include adding a new model, changing and existing model or terrain, deleting an existing model, replacing an existing model. From the discussion in the participant reports, there was no standard for executing those operations. The HTTP standard defines the methods `GET` (retrieve), `POST` (add new), `PUT` (replace existing), `PATCH` (update), and `DELETE` (delete) request methods that can be used for these operations. Ecere discusses the operation in detail in <<Updating the 3D content>>.

==== Media Type

The HTTP specification allows the client to specify the allowed media types that the server is allowed to return. The server may return a "Not Found" or other responses if the requested media type for that content is not available. If the various 3D data types have unique media types, the client may request a specific one through this mechanism. Helyx discussed some of these options in <<Representing Alternate Distributions as Media Types>>.

NOTE: Media types do not have to be approved by Internet Assigned Numbers Authority (IANA). There are provision for experimental and vendor-specific content types. It is generally easier to get IANA approval after a specification is approved by standards organization.

==== Request Attributes

HTTP allows for an alternate or roll-over reference. This allows for the client code to indicate alternate distributions of the content-equivalent data. For example the primary reference may be 3D Tiles with a roll-over of i3s and CDB. Helyx discussed some of the issues and options in <<Representing Alternate Distributions within one API - Link Relations>>.

==== Other Friction Points

InfoDao noted that (<<GeoVolumes API Discussion: CDB comparisons and OGC API discussion>>) CDB and GeoVolumes APIs exist separately, but need to work together. The existing specifications (draft and approved) allow that to happen. There are issues with knowledge of the data structures are not necessarily known or easily handled on both the client and server sides of the communication link.

=== Game Engine Interface

SimBlocks.io worked on integrating their solution into the Unity game engine. There was quite a bit of work to do bringing in the 3D data as glTF or 3D Tiles into Unity. The solution they developed during the Sprint is sub-optimal, but it did work. They reported that they felt the solution for the Unreal engine would likely require a similar amount of work.
